name: Trigger auto deployment for miabe-expresssample9e01

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/miabe-expresssample9e01-AutoDeployTrigger-6f18d403-f561-4ec6-b89c-b12aaff08956.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MIABEEXPRESSSAMPLE9E01_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MIABEEXPRESSSAMPLE9E01_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MIABEEXPRESSSAMPLE9E01_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.MIABEEXPRESSSAMPLE9E01_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MIABEEXPRESSSAMPLE9E01_REGISTRY_PASSWORD }}
          containerAppName: miabe-expresssample9e01
          resourceGroup: firststaticwebapp8032
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


